### ISSUE TITLE
Simplifing (and implementing) UI (front end)

### ISSUE THREAD

**Issue by csabe812** [csabe812/Agrovetel#14]
As a developer I would like to materialize the UI.
Tasks:
- [x] unified header
- [x] unified footer
- [x] content in the middle
- [x] admin site ?

**Comment by csabe812** [comment]
Need to discuss: [link](https://github.com/csabe812/Agrovetel/wiki/Meeting-notes-09th-April-2019)
@kafr007 what is your opinion?
At first I would recommend option (1)

**Comment by kafr007** [comment]
Yes, I recommed the first option, too.

**Comment by csabe812** [comment]
First part: 05ef8293957742f2a0cabd21e8e45477cf710baf

**Comment by csabe812** [comment]
First part: 05ef8293957742f2a0cabd21e8e45477cf710baf

**Comment by csabe812** [comment]
05ef8293957742f2a0cabd21e8e45477cf710baf

**Comment by csabe812** [comment]
Closed beacuse the main part of the UI has been successfully activated at 5861f3c1f8e5e1b6e190a349708e8aa693e99fec
