### ISSUE TITLE
Number of visitors

### ISSUE THREAD

**Issue by csabe812** [csabe812/Agrovetel#15]
As a User I would like to be informed about the number of the current ad's visitors.

**Comment by csabe812** [comment]
Ads table needs one more column (numberOfVisitors).
Every findById(long id) call increments the numberOfVisitors.

**Comment by kafr007** [comment]
TODO create tests

**Comment by csabe812** [comment]
Created a "dummy client" at `/ads` and all the ads will be displayed. Clicking "details" increments the `numberOfVisitors` attribute so everything works fine.
