### ISSUE TITLE
Listing Ads by categoryId

### ISSUE THREAD

**Issue by csabe812** [csabe812/Agrovetel#8]
As a user I want to list the ads sort by category.

**Comment by kafr007** [comment]
Create a List<Ad> findAllByCategory(Long categoryId) method in AdService. Is it enough, or we need this method too: List<Ad> findAllByCategory(String categoryName) ? @csabe812

**Comment by kafr007** [comment]
TODO test

**Comment by csabe812** [comment]
> Create a List findAllByCategory(Long categoryId) method in AdService. Is it enough, or we need this method too: List findAllByCategory(String categoryName) ? @csabe812

It's your choice... If you would like to create a findAllByCategory(), then categoryname should by unique.
